# make file for sky
OS := $(shell uname)

.DEFAULT: default
default: install fmt lint vet test

.PHONY: install_lint
install_lint:
	@echo "Running: $@"

	@go get -u github.com/golang/lint/golint
	@cd $$GOPATH/src/github.com/golang/lint/golint && go install .

.PHONY: lint
lint:
	@echo "Running: $@"
	@echo "Running: $@"
#   _sting.go is generated by go's stringer.
	@test -z "$$(golint ./... | grep -v vendor/ | grep -v "_string.go" | tee /dev/stderr)"


.PHONY: fmt
fmt:
	@echo "Running: $@"
	@test -z "$$(gofmt -l . |  grep -v vendor/ | tee /dev/stderr)"  || (echo "'gofmt' required on the above files" && false)

.PHONY: fmtv
fmtv:
	@echo "Running: $@"
	@test -z "$$(gofmt -d . |  grep -v vendor/ | tee /dev/stderr)"  || (echo "'gofmt' required on the above files" && false)

.PHONY: install
install:
	@echo "Running: $@"
	@dep ensure
	@go install -a ./...

.PHONY: vet
vet:
	@echo "Running: $@"
	@go list ./... | grep -v /vendor/ | xargs -L1 go vet

.PHONY: test
test:
	@echo "Running: $@"
	go test ./... -v


